# Config file for automatic testing at travis-ci.org

language: python
dist: xenial

python:
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"

env:
  - TOX_ENV=django-22
  - TOX_ENV=django-31
  - TOX_ENV=django-32

matrix:
  fast_finish: true

# command to install dependencies
install: pipenv install --dev

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
